version: '3.8'

services:
  minio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - minio-net

volumes:
  minio_data:
    driver: local

networks:
  minio-net:
    driver: bridge